name: Spec CI
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install --upgrade pip jsonschema || true
      - run: python tools/validate.py || echo "no validator yet"
